version: '1.0'
name: pipeline-20241008
displayName: pipeline-20241008
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: cargo_build
    displayName: cargo 构建
    strategy: naturally
    trigger: auto
    executor:
      - zerokit
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 14.16.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && cargo tauri build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
