name: Build and Release Tauri App

on:
  push:
    branches:
      - master  # 或者其他你想要触发编译的分支

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Rust
        uses: rust-lang/setup-rust@v1  # 使用 rust-lang/setup-rust
        with:
          rust-version: stable

      - name: Install dependencies
        run: |
          npm ci
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

      - name: Install Tauri CLI
        run: |
          cargo install tauri-cli

      - name: Install Tauri dependencies for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libssl-dev pkg-config libgtk-3-dev

      - name: Install Tauri dependencies for Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install windows-sdk-10.1

      - name: Install Tauri dependencies for macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install libtool automake cmake

      - name: Build Tauri app for ${{ matrix.os }} ${{ matrix.arch }}
        run: |
          npx tauri build --arch ${{ matrix.arch }} --release

      - name: Archive the release assets
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            zip -r tauri-linux-${{ matrix.arch }}.zip ./src-tauri/target/release/bundle/
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            zip -r tauri-windows-${{ matrix.arch }}.zip ./src-tauri/target/release/bundle/
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            zip -r tauri-macos-${{ matrix.arch }}.zip ./src-tauri/target/release/bundle/
          fi

      - name: Upload release assets to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          files: |
            tauri-linux-${{ matrix.arch }}.zip
            tauri-windows-${{ matrix.arch }}.zip
            tauri-macos-${{ matrix.arch }}.zip
